/**
 * callback function kmdsFontsLoad();
 * to load kmds fonts before JSON render at canvas
 * @return ''
 **/
function kmdsFontsLoad(fontName = null) {
  var kmdsFonts = {
    'Abel': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Abel/Abel.woff2',
    'Abril Fatface': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Abril+Fatface/Abril+Fatface.woff2',
    'Alegreya': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Alegreya/Alegreya.woff2',
    'Alice': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Alice/Alice.woff2',
    'Alice Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/AliceLight/AliceLight.woff2', 
    'Amaranth': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Amaranth/Amaranth.woff2',
    'Amatic SC': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Amatic+SC/Amatic+SC.woff2', 
    'Baloo': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Baloo/Baloo-Regular.woff2',
    'Cantarell': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Cantarell+Regular/Cantarell+Regular.woff2',
    'Cantarell Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Cantarell+Bold/Cantarell+Bold.woff2',
    'Cherry Cream Soda': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Cherry+Cream+Soda/Cherry+Cream+Soda.woff2',
    'Corben': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Corben+Regular/Corben+Regular.woff2',
    //'Coustard Ultra': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Ultra/Ultra.woff2',
    'Coustard': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Coustard/Coustard.woff2',
    'CQ Mono': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/CQ+Mono/CQ+Mono.woff2',
    'Dancing Script': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Dancing+Script/Dancing+Script.woff2',
    'Dancing Script Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Dancing+Script+Bold/Dancing+Script+Bold.woff2',
    'Dosis': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Dosis-Regular/Dosis-Regular.woff2',
    'Dosis Bold': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Dosis-Bold/Dosis-Bold.woff2',
    //'Dosis SemiBold': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Dosis-SemiBold/Dosis-SemiBold.woff2',
    //'Dosis ExtraBold': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Dosis-ExtraBold/Dosis-ExtraBold.woff2',
    //'Dosis Light': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Dosis-Light/Dosis-Light.woff2',
    'Dosis ExtraLight': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Dosis-ExtraLight/Dosis-ExtraLight.woff2',
    //'Dosis Medium': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Dosis-Medium/Dosis-Medium.woff2',
    'Droid Serif': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Droid+Serif/Droid+Serif.woff2',
    'EB Garamond': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/EB+Garamond/EB+Garamond.woff2',
    'EB Garamond Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/EB+Garamond+Bold/EB+Garamond+Bold.woff2',
    'Elsie': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Elsie/Elsie.woff2',
    'Exo': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Exo+2.0/Exo+2.0.woff2',
    'Exo Black': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Exo+Black/Exo+Black.woff2',
    'Exo Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Exo+Bold/Exo+Bold.woff2',
    'Exo Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Exo+Italic/Exo+Italic.woff2',
    'Exo Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Exo+Light/Exo+Light.woff2',
    'Exo Medium': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Exo+Medium/Exo+Medium.woff2',
    'Exo Thin': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Exo+Thin/Exo+Thin.woff2',
    'Fjalla One': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Fjalla+One/Fjalla+One.woff2',
    'Grand Hotel': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Grand+Hotel/Grand+Hotel.woff2',
    'Josefin Sans': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+Regular/Josefin+Sans+Regular.woff2',
    'Josefin Sans Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+Bold/Josefin+Sans+Bold.woff2',
    'Josefin Sans Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+Bold+Italic/Josefin+Sans+Bold+Italic.woff2',
    'Josefin Sans Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+Italic/Josefin+Sans+Italic.woff2',
    'Josefin Sans Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+Light/Josefin+Sans+Light.woff2',
    'Josefin Sans Light Italic': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+Light+Italic/JosefinSans-LightItalic.woff2',
    'Josefin Sans SemiBold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+SemiBold/Josefin+Sans+SemiBold.woff2',
    'Josefin Sans SemiBold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+SemiBold+Italic/Josefin+Sans+SemiBold+Italic.woff2',
    'Josefin Sans Thin': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+Thin/Josefin+Sans+Thin.woff2',
    'Josefin Sans Thin Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Josefin+Sans+Thin+Italic/Josefin+Sans+Thin+Italic.woff2',
    'Lato': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Lato+Regular/Lato+Regular.woff2',
    'Lato Medium': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Lato+Medium/Lato+Medium.woff2',
    'Lato Black': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Lato+Black/Lato+Black.woff2',
    'Lato Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Lato+Bold/Lato+Bold.woff2',
    'Lato Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Lato+Light/Lato+Light.woff2',
    'Lato Thin': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Lato+Thin/Lato+Thin.woff2',
    'Leckerli One': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Leckerli+One/Leckerli+One.woff2',
    'Libre Baskerville': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Libre+Baskerville/Libre+Baskerville.woff2',
    'Libre Baskerville Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Libre+Baskerville+Bold/Libre+Baskerville+Bold.woff2',
    'Libre Baskerville Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Libre+Baskerville+Italic/Libre+Baskerville+Italic.woff2',
    'Lora': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Lora/Lora.woff2',
    'Medula One': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Medula+One/Medula+One.woff2',
    'Merriweather': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Merriweather/Merriweather.woff2',
    'Merriweather Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Merriweather+Bold/Merriweather+Bold.woff2',
    'Merriweather Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Merriweather+Light/Merriweather+Light.woff2',
    'Merriweather Black': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Merriweather-Black/Merriweather-Black.woff2',
    'Montserrat': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Montserrat+Regular/Montserrat+Regular.woff2',
    'Montserrat Black': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Montserrat+Black/Montserrat+Black.woff2',
    'Montserrat Hairline': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Montserrat+Hairline/Montserrat+Hairline.woff2',
    'Montserrat Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Montserrat+Italic/Montserrat+Italic.woff2',
    'Montserrat Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Montserrat+Bold/Montserrat+Bold.woff2',
    'Montserrat Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Montserrat+Light/Montserrat+Light.woff2',
    'Montserrat SemiBold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Montserrat+SemiBold/Montserrat+SemiBold.woff2',
    'Montserrat Thin': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Montserrat+Thin/Montserrat+Thin.woff2',
    'Muli': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Muli/Muli.woff2',
    'Muli Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Muli+Bold/Muli+Bold.woff2',
    'Muli Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Muli+Light/Muli+Light.woff2',
    'Muli Light Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Muli+Light+Italic/Muli+Light+Italic.woff2',
    'Nobile': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Nobile/Nobile.woff2',
    'Nobile Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Nobile+Bold/Nobile+Bold.woff2',
    'Nobile Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Nobile+Bold+Italic/Nobile+Bold+Italic.woff2',
    'Nobile Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Nobile+Italic/Nobile+Italic.woff2',
    'Noto Sans': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/NotoSans/NotoSans-Regular.woff2',
    'Noto Sans Bold': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/NotoSans-Bold/NotoSans-Bold.woff2',
    'Noto Sans Bold Italic': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/NotoSans-BoldItalic/NotoSans-BoldItalic.woff2',
    'Noto Sans Italic': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/NotoSans-Italic/NotoSans-Italic.woff2',
    'Open Sans': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Open+Sans/Open+Sans.woff2',
    'Open Sans Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Open+Sans+Bold/Open+Sans+Bold.woff2',
    'Open Sans Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Open+Sans+Italic/Open+Sans+Italic.woff2',
    'Open Sans Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Open+Sans+Light/Open+Sans+Light.woff2',
    'Open Sans Semibold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Open+Sans+Semibold/Open+Sans+Semibold.woff2',
    'Open Sans Condensed Light':'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Open+Sans+Condensed+Light+Regular/Open+Sans+Condensed+Light+Regular.woff2',
    'Oswald': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Oswald/Oswald.woff2',
    'Oswald Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Oswald+Bold/Oswald+Bold.woff2',
    'Oswald Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Oswald+Light/Oswald+Light.woff2',
    'Oswald SemiBold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Oswald+SemiBold/Oswald+SemiBold.woff2',
    'Palanquin Dark Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Palanquin+Dark+Bold/Palanquin+Dark+Bold.woff2',
    'Philosopher': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Philosopher/Philosopher.woff2',
    'Philosopher Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Philosopher+Bold/Philosopher+Bold.woff2',
    'Philosopher Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Philosopher+Italic/Philosopher+Italic.woff2',
    'Philosopher Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Philosopher+Bold+Italic/Philosopher+Bold+Italic.woff2',
    'Playfair Display Black': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Playfair+Display+Black/Playfair+Display+Black.woff2',
    'Playfair Display Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Playfair+Display+Bold/Playfair+Display+Bold.woff2',
    'Playfair Display Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Playfair+Display+Italic/Playfair+Display+Italic.woff2',
    'Playfair Display': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Playfair+Display/Playfair+Display.woff2',
    'Playfair Display Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Playfair+Display+Bold+Italic/Playfair+Display+Bold+Italic.woff2',
    'Poppins': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Poppins/Poppins.woff2',
    'Poppins Black': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Poppins+Black/Poppins+Black.woff2',
    'Poppins Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Poppins+Bold/Poppins+Bold.woff2',
    'Poppins Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Poppins+Light/Poppins+Light.woff2',
    'Poppins SemiBold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Poppins+SemiBold/Poppins+SemiBold.woff2',
    'Poppins Thin': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Poppins+Thin/Poppins+Thin.woff2',
    'PT Sans': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/PT+Sans/PT+Sans.woff2',
    'PT Sans Narrow': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/PT+Sans+Narrow/PT+Sans+Narrow.woff2',
    'PT Sans Narrow Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/PT+Sans+Narrow+Bold/PT+Sans+Narrow+Bold.woff2',
    'Quattrocento Sans': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Quattrocento+Sans/Quattrocento+Sans.woff2',
    'Quattrocento Sans Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Quattrocento+Sans+Bold/Quattrocento+Sans+Bold.woff2',
    'Quattrocento Sans Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Quattrocento+Sans+Italic/Quattrocento+Sans+Italic.woff2',
    'Quattrocento Sans Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Quattrocento+Sans+Bold+Italic/Quattrocento+Sans+Bold+Italic.woff2',
    'Raleway': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Raleway/Raleway.woff2',
    'Raleway Black': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Raleway+Black/Raleway+Black.woff2',
    'Raleway Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Raleway+Bold/Raleway+Bold.woff2',
    'Raleway Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Raleway+Italic/Raleway+Italic.woff2',
    'Raleway Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Raleway+Light/Raleway+Light.woff2',
    'Raleway SemiBold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Raleway+SemiBold/Raleway+SemiBold.woff2',
    'Raleway Thin': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Raleway+Thin/Raleway+Thin.woff2',
    'Roboto': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto/Roboto.woff2',
    'Roboto Black': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto+Black/Roboto+Black.woff2',
    'Roboto Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto+Bold/Roboto+Bold.woff2',
    'Roboto Thin': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto+Thin/Roboto+Thin.woff2',
    'Roboto Regular': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto+Regular/Roboto+Regular.woff2',
    'Roboto Condensed': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto+Condensed/Roboto+Condensed.woff2',
    'Roboto Condensed Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto+Condensed+Bold/Roboto+Condensed+Bold.woff2',
    'Roboto Condensed Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto+Condensed+Light/Roboto+Condensed+Light.woff2',
    'Roboto Condensed Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto+Condensed+Bold+Italic/Roboto+Condensed+Bold+Italic.woff2',
    'Roboto Condensed Light Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Roboto+Condensed+Light+Italic/Roboto+Condensed+Light+Italic.woff2',
    'Roboto Slab': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/RobotoSlab-Regular/RobotoSlab-Regular.woff2',
    'Roboto Slab Black': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/RobotoSlab-Black/RobotoSlab-Black.woff2',
    'Roboto Slab Thin': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/RobotoSlab-Thin/RobotoSlab-Thin.woff2',
    'Roboto Slab Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/RobotoSlab-Light/RobotoSlab-Light.woff2',
    'Roboto Slab Extra Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/RobotoSlab-ExtraLight/RobotoSlab-ExtraLight.woff2',
    'Roboto Slab Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/RobotoSlab-Bold/RobotoSlab-Bold.woff2',
    'Roboto Slab Semi Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/RobotoSlab-SemiBold/RobotoSlab-SemiBold.woff2',
    'Roboto Slab Extra Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/RobotoSlab-ExtraBold/RobotoSlab-ExtraBold.woff2',
    'Roboto Slab Medium': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/RobotoSlab-Medium/RobotoSlab-Medium.woff2',
    'Sansita': 'https://s3-us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Sansita-Regular/Sansita-Regular.woff2',
    'Six Caps': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Six+Caps/Six+Caps.woff2',
    'Source Sans Pro': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Source+Sans+Pro/Source+Sans+Pro.woff2',
    'Space Mono': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Space+Mono/Space+Mono.woff2',
    'Space Mono Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Space+Mono+Bold/Space+Mono+Bold.woff2',
    'Space Mono Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Space+Mono+Italic/Space+Mono+Italic.woff2',
    'Spirax': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Spirax-Regular/Spirax-Regular.woff2',
    'Vollkorn': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Vollkorn/Vollkorn.woff2',
    'Vollkorn Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Vollkorn+Bold/Vollkorn+Bold.woff2',
    'Vollkorn Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Vollkorn+Italic/Vollkorn+Italic.woff2',
    'Vollkorn Semibold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Vollkorn+Semibold/Vollkorn+Semibold.woff2',
    'Vollkorn Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Vollkorn+Bold+Italic/Vollkorn+Bold+Italic.woff2',
    'American Typewriter': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/American+Typewriter/American+Typewriter+Regular.woff2',
    'Andale Mono': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Andale+Mono/Andale+Mono.woff2',
    'Arial Black': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Arial/Arial+Black.woff2',
    'Arial': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Arial/Arial.woff2',
    'Arial Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Arial/Arial+Bold.woff2',
    'Arial Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Arial/Arial+Bold+Italic.woff2',
    'Arial Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Arial/Arial+Italic.woff2',
    'Arial Narrow Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Arial/Arial+Narrow+Bold+Italic.woff2',
    'Arial Narrow Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Arial/Arial+Narrow+Bold.woff2',
    'Arial Narrow Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Arial/Arial+Narrow+Italic.woff2',
    'Arial Narrow': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Arial/Arial+Narrow.woff2',
    'Bradley Hand': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Bradley+Hand/Bradley+Hand.woff2',
    'Bradley Hand Negrita': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Bradley+Hand/Bradley+Hand+Negrita.woff2',
    'Brush Script MT': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Brush+Script+MT/Brush+Script+MT.woff2',
    'Comic Sans MS Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Comic+Sans+MS/Comic+Sans+MS+Bold.woff2',
    'Comic Sans MS Italic Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Comic+Sans+MS/Comic+Sans+MS+Italic+Bold.woff2',
    'Comic Sans MS Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Comic+Sans+MS/Comic+Sans+MS+Italic.woff2',
    'Comic Sans MS': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Comic+Sans+MS/Comic+Sans+MS.woff2',
    'Courier': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Courier/Courier.woff2',
    'Courier Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Courier/Courier+Italic.woff2',
    'Courier Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Courier/Courier+Bold.woff2',
    'Courier Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Courier/Courier+Bold+Italic.woff2',
    'Didot Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Didot/Didot+Bold+Italic.woff2',
    'Didot Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Didot/Didot+Bold.woff2',
    'Didot Light Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Didot/Didot+Light+Italic.woff2',
    'Didot Light': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Didot/Didot+Light.woff2',
    'Didot Medium Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Didot/Didot+Medium+Italic.woff2',
    'Didot Medium':  'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Didot/Didot+Medium.woff2',
    'Georgia': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Georgia/Georgia.woff2',
    'Georgia Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Georgia/Georgia+Italic.woff2',
    'Georgia Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Georgia/Georgia+Bold.woff2',
    'Georgia Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Georgia/Georgia+Bold+Italic.woff2',
    'Impact': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Impact/Impact.woff2',
    'Lucida Console Regular': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Lucida+Console/Lucida+Console+Regular.woff2',
    'Luminari Regular': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Luminari/Luminari+Regular.woff2',
    'Monaco': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Monaco/Monaco.woff2',
    'Tahoma': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Tahoma/Tahoma.woff2',
    'Tahoma Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Tahoma/Tahoma+Bold.woff2',
    'Times New Roman': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Times+New+Roman/Times+New+Roman.woff2',
    'Times New Roman Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Times+New+Roman/Times+New+Roman+Italic.woff2',
    'Times New Roman Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Times+New+Roman/Times+New+Roman+Bold.woff2',
    'Times New Roman Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Times+New+Roman/Times+New+Roman+Bold+Italic.woff2',
    'Trebuchet MS': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Trebuchet+MS/Trebuchet+MS.woff2',
    'Trebuchet MS Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Trebuchet+MS/Trebuchet+MS+Italic.woff2',
    'Trebuchet MS Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Trebuchet+MS/Trebuchet+MS+Bold.woff2',
    'Trebuchet MS Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Trebuchet+MS/Trebuchet+MS+Bold+Italic.woff2',
    'Verdana': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Verdana/Verdana.woff2',
    'Verdana Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Verdana/Verdana+Italic.woff2',
    'Verdana Bold': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Verdana/Verdana+Bold.woff2',
    'Verdana Bold Italic': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/Verdana/Verdana+Bold+Italic.woff2',
    'Wendy One': 'https://s3.us-west-2.amazonaws.com/kaboodlemedia.com/s3fs_public/kmdsFonts/WendyOne/WendyOne.woff2',
  };
  if(fontName == null){
    //var count = kmdsFonts.length;
    var count = Object.keys(kmdsFonts).length
    jQuery.each(kmdsFonts, function(key, val){
      var kmdsFont = new FontFace(key, 'url('+val+')');
      kmdsFont.load().then(function(font){
        document.fonts.add(font);
        count--;
        //console.log(key+' Font done');
        //jQuery("#canvasFontFamily").append('<span style="font-family: \''+key+'\'">&nbsp;</span>');
        if(count == 0){
          console.log('Font loading done');
          fabric.util.clearFabricFontCache();
          var added_json = canvas.toJSON();
          canvas.clear();
          canvas.loadFromJSON(added_json, canvas.renderAll.bind(canvas));
          //Refresh container image coords
          setTimeout(function () {
            if(jQuery("#containerDefaultImage").length){
              updateContainerImageCoords();
            }
            if(jQuery("#displayed-page").length){
              if(pageArr.length > 1){
                enabledTemplateFirstPageObjects();
              }
            }
          }, 100);
        }
      });
    });
  }
  else {
    var kmdsFont = new FontFace(fontName, 'url('+kmdsFonts[fontName]+')');
    kmdsFont.load().then(function(font){
      document.fonts.add(font);
      console.log(fontName+' Font loaded');
      fabric.util.clearFabricFontCache(fontName);
      var added_json = canvas.toJSON();
      canvas.clear();
      canvas.loadFromJSON(added_json, canvas.renderAll.bind(canvas));
      //Refresh container image coords
      setTimeout(function () {
        if(jQuery("#containerDefaultImage").length){
          updateContainerImageCoords();
        }
        if(jQuery("#displayed-page").length){
          if(pageArr.length > 1){
            enabledTemplateFirstPageObjects();
          }
        }
      }, 100);
    });
  }
}
/**
 * callback function kmdsFontsList();
 * to get all fonts name and their type
 * @return @fonts
 **/
function kmdsFontsList(fontName = null) {
  var kmdsFontsList = {
    "Abel" : ["Regular"],
    "Abril Fatface" : ["Regular"],
    "Alegreya" : ["Regular"],
    "Alice" : ["Regular", "Light"],
    "Amaranth" : ["Regular"],
    "Amatic SC" : ["Regular"],
    "American Typewriter" : ["Regular"],
    "Andale Mono" : ["Regular"],
    "Arial" : ["Regular", "Black", "Bold", "Bold Italic", "Italic", "Narrow Bold Italic", "Narrow Bold", "Narrow Italic", "Narrow"],
    "Baloo" : ["Regular"],
    "Bradley Hand" : ["Regular", "Negrita"],
    "Brush Script MT" : ["Regular"],
    "Cantarell" : ["Regular", "Bold"],
    "Cherry Cream Soda" : ["Regular"],
    "Comic Sans MS" : ["Regular", "Bold", "Italic Bold", "Italic"],
    "Corben" : ["Regular"],
    //"Coustard Ultra" : ["Regular"],    
    "Courier" : ["Regular", "Italic", "Bold", "Bold Italic"],
    "Coustard" : ["Regular"],
    "CQ Mono" : ["Regular"],
    "Dancing Script" : ["Regular", "Bold"],
    //"Dosis" : ["Regular", "Bold", "SemiBold", "ExtraBold", "Light", "ExtraLight", "Medium"],
    "Didot" : ["Medium", "Medium Italic", "Light", "Light Italic", "Bold", "Bold Italic"],
    "Dosis" : ["Regular", "Bold", "ExtraLight"],
    "Droid Serif" : ["Regular"],
    "EB Garamond" : ["Regular", "Bold"],
    "Elsie" : ["Regular"],
    "Exo" : ["Regular", "Black", "Bold", "Italic", "Light", "Medium", "Thin"],
    "Fjalla One" : ["Regular"],
    "Georgia" : ["Regular", "Bold", "Italic", "Bold Italic"],
    "Grand Hotel" : ["Regular"],
    "Impact" : ["Regular"],
    "Josefin Sans" : ["Regular", "Bold", "Italic", "Bold Italic", "Light", "Light Italic", "SemiBold", "SemiBold Italic", "Thin", "Thin Italic"],
    "Lato" : ["Regular", "Medium", "Black", "Bold", "Light", "Thin"],
    "Leckerli One" : ["Regular"],
    "Libre Baskerville" : ["Regular", "Bold", "Italic"],
    "Lora" : ["Regular"],
    "Lucida Console" : ["Regular"],
    "Luminari" : ["Regular"],
    "Medula One" : ["Regular"],
    "Merriweather" : ["Regular", "Bold", "Light", "Black"],
    "Monaco" : ["Regular"],
    "Montserrat" : ["Regular", "Black", "Hairline", "Italic", "Bold", "Light", "SemiBold", "Thin"],
    "Muli" : ["Regular", "Bold", "Light", "Light Italic"],
    "Nobile" : ["Regular", "Bold", "Bold Italic", "Italic"],
    "Noto Sans" : ["Regular", "Bold", "Italic", "Bold Italic"],
    "Open Sans" : ["Regular", "Bold", "Italic", "Light", "Semibold", "Condensed Light"],
    "Oswald" : ["Regular", "Bold", "Light", "SemiBold"],
    "Palanquin Dark Bold" : ["Regular"],
    "Philosopher" : ["Regular", "Bold", "Italic", "Bold Italic"],
    "Playfair Display" : ["Regular", "Black", "Bold", "Italic", "Bold Italic"],
    "Poppins" : ["Regular", "Black", "Bold", "Light", "SemiBold", "Thin"],
    "PT Sans" : ["Regular", "Narrow", "Narrow Bold"],
    "Quattrocento Sans" : ["Regular", "Bold", "Italic", "Bold Italic"],
    "Raleway" : ["Regular", "Black", "Bold", "SemiBold", "Italic", "Light", "Thin"],
    "Roboto" : ["Regular", "Black", "Bold", "Thin"],
    "Roboto Condensed" : ["Regular", "Bold", "Light", "Bold Italic", "Light Italic"],
    "Roboto Slab" : ["Regular", "Black", "Thin", "Light", "Extra Light", "Bold", "Semi Bold", "Extra Bold", "Medium"],
    "Sansita" : ["Regular"],
    "Six Caps" : ["Regular"],
    "Source Sans Pro" : ["Regular"],
    "Space Mono" : ["Regular", "Bold", "Italic"],
    "Spirax" : ["Regular"],
    "Tahoma" : ["Regular", "Bold"],
    "Times New Roman" : ["Regular", "Bold", "Italic", "Bold Italic"],
    "Trebuchet MS" : ["Regular", "Bold", "Italic", "Bold Italic"],    
    "Verdana" : ["Regular", "Bold", "Italic", "Bold Italic"],
    "Vollkorn" : ["Regular", "Bold", "Italic", "Semibold", "Bold Italic"],
    "Wendy One" : ["Regular"],
  }
  if(fontName == null){
    var fonts = jQuery.map(kmdsFontsList, function(element,index) {return index});
    return fonts;
  }
  else{
    return kmdsFontsList[fontName]
  }
}
/**
 * Callback function addFontStyle()
 * to add font style in #fstyle
 **/
function addFontStyle(fontName, styleName = null){
  if(jQuery("#fstyle").length){
    jQuery("#fstyle").empty();
    var fstyle = kmdsFontsList(fontName);
    var count = fstyle.length;
    jQuery.each(fstyle, function(key, val){
      jQuery("#fstyle").append('<option value="'+val+'">'+val+'</option>');
      if(styleName != null && key == parseInt(count-1)){
        //console.log("addFontStyle = "+styleName);
        document.getElementById('fstyle').value = styleName;
      }
    });
  }
}
/**
 * callback function kmdsFontsStyleList();
 * to get font style
 * @return @style
 **/
function kmdsFontsStyleList(fontName = null) {
  var kmdsFontsStyleList = {
    "Abel" : ["Abel", "Regular"],
    "Abril Fatface" : ["Abril Fatface", "Regular"],
    "Alegreya" : ["Alegreya", "Regular"],
    "Alice" : ["Alice", "Regular"],
    "Alice Light" : ["Alice", "Light"],
    "Amaranth" : ["Amaranth", "Regular"],
    "Amatic SC" : ["Amatic SC", "Regular"],
    "American Typewriter" : ["American Typewriter", "Regular"],
    "Andale Mono" : ["Andale Mono", "Regular"],
    "Arial" : ["Arial", "Regular"],
    "Arial Black" : ["Arial", "Black"],
    "Arial Bold" : ["Arial", "Bold"],
    "Arial Bold Italic" : ["Arial", "Bold Italic"],
    "Arial Italic" : ["Arial", "Italic"],
    "Arial Narrow Bold Italic" : ["Arial", "Narrow Bold Italic"],
    "Arial Narrow Bold" : ["Arial", "Narrow Bold"],
    "Arial Narrow Italic" : ["Arial", "Narrow Italic"],
    "Arial Narrow" : ["Arial", "Narrow"],
    "Baloo" : ["Baloo", "Regular"],
    "Bradley Hand" : ["Bradley Hand", "Regular"],
    "Bradley Hand Negrita" : ["Bradley Hand", "Negrita"],
    "Brush Script MT" : ["Brush Script MT", "Regular"],
    "Cantarell" : ["Cantarell", "Regular"],
    "Cantarell Bold" : ["Cantarell", "Bold"],
    "Cherry Cream Soda" : ["Cherry Cream Soda", "Regular"],
    "Comic Sans MS" : ["Comic Sans MS", "Regular"],
    "Comic Sans MS Bold" : ["Comic Sans MS", "Bold"],
    "Comic Sans MS Italic Bold" : ["Comic Sans MS", "Italic Bold"],
    "Comic Sans MS Italic" : ["Comic Sans MS", "Italic"],    
    "Corben" : ["Corben", "Regular"],
    //"Coustard Ultra" : ["Coustard Ultra", "Regular"],
    "Courier" : ["Courier", "Regular"],
    "Courier Italic" : ["Courier", "Italic"],
    "Courier Bold" : ["Courier", "Bold"],
    "Courier Bold Italic" : ["Courier", "Bold Italic"],
    "Coustard" : ["Coustard", "Regular"],
    "CQ Mono" : ["CQ Mono", "Regular"],
    "Dancing Script" : ["Dancing Script", "Regular"],
    "Dancing Script Bold" : ["Dancing Script", "Bold"],
    "Didot Medium" : ["Didot", "Medium"],
    "Didot Medium Italic" : ["Didot", "Medium Italic"],
    "Didot Light" : ["Didot", "Light"],
    "Didot Light Italic" : ["Didot", "Light Italic"],
    "Didot Bold" : ["Didot", "Bold"],
    "Didot Bold Italic" : ["Didot", "Bold Italic"],
    "Dosis" : ["Dosis", "Regular"],
    "Dosis" : ["Dosis", "Bold"],
    //"Dosis" : ["Dosis", "SemiBold"],
    //"Dosis" : ["Dosis", "ExtraBold"],
    //"Dosis" : ["Dosis", "Light"],
    "Dosis" : ["Dosis", "ExtraLight"],
    //"Dosis" : ["Dosis", "Medium"],
    "Droid Serif" : ["Droid Serif", "Regular"],
    "EB Garamond" : ["EB Garamond", "Regular"],
    "EB Garamond Bold" : ["EB Garamond", "Bold"],
    "Elsie" : ["Elsie", "Regular"],
    "Exo" : ["Exo", "Regular"],
    "Exo Black" : ["Exo", "Black"],
    "Exo Bold" : ["Exo", "Bold"],
    "Exo Italic" : ["Exo", "Italic"],
    "Exo Light" : ["Exo", "Light"],
    "Exo Medium" : ["Exo", "Medium"],
    "Exo Thin" : ["Exo", "Thin"],
    "Fjalla One" : ["Fjalla One", "Regular"],
    "Georgia" : ["Georgia", "Regular"],
    "Georgia Bold" : ["Georgia", "Bold"],
    "Georgia Italic" : ["Georgia", "Italic"],
    "Georgia Bold Italic" : ["Georgia", "Bold Italic"],
    "Grand Hotel" : ["Grand Hotel", "Regular"],
    "Impact" : ["Impact", "Regular"],
    "Josefin Sans" : ["Josefin Sans", "Regular"],
    "Josefin Sans Bold" : ["Josefin Sans", "Bold"],
    "Josefin Sans Italic" : ["Josefin Sans", "Italic"],
    "Josefin Sans Bold Italic" : ["Josefin Sans", "Bold Italic"],
    "Josefin Sans Light" : ["Josefin Sans", "Light"],
    "Josefin Sans Light Italic" : ["Josefin Sans", "Light Italic"],
    "Josefin Sans SemiBold" : ["Josefin Sans", "SemiBold"],
    "Josefin Sans SemiBold Italic" : ["Josefin Sans", "SemiBold Italic"],
    "Josefin Sans Thin" : ["Josefin Sans", "Thin"],
    "Josefin Sans Thin Italic" : ["Josefin Sans", "Thin Italic"],
    "Lato" : ["Lato", "Regular"],
    "Lato Medium" : ["Lato", "Medium"],
    "Lato Black" : ["Lato", "Black"],
    "Lato Bold" : ["Lato", "Bold"],
    "Lato Light" : ["Lato", "Light"],
    "Lato Thin" : ["Lato", "Thin"],
    "Leckerli One" : ["Leckerli One", "Regular"],
    "Libre Baskerville" : ["Libre Baskerville", "Regular"],
    "Libre Baskerville Bold" : ["Libre Baskerville", "Bold"],
    "Libre Baskerville Italic" : ["Libre Baskerville", "Italic"],
    "Lora" : ["Lora", "Regular"],
    "Lucida Console" : ["Lucida Console", "Regular"],
    "Luminari" : ["Luminari", "Regular"],
    "Medula One" : ["Medula One", "Regular"],
    "Merriweather" : ["Merriweather", "Regular"],
    "Merriweather Bold" : ["Merriweather", "Bold"],
    "Merriweather Light" : ["Merriweather", "Light"],
    "Merriweather Black" : ["Merriweather", "Black"],
    "Monaco" : ["Monaco", "Regular"],
    "Montserrat" : ["Montserrat", "Regular"],
    "Montserrat Black" : ["Montserrat", "Black"],
    "Montserrat Hairline" : ["Montserrat", "Hairline"],
    "Montserrat Italic" : ["Montserrat", "Italic"],
    "Montserrat Bold" : ["Montserrat", "Bold"],
    "Montserrat Light" : ["Montserrat", "Light"],
    "Montserrat SemiBold" : ["Montserrat", "SemiBold"],
    "Montserrat Thin" : ["Montserrat", "Thin"],
    "Muli" : ["Muli", "Regular"],
    "Muli Bold" : ["Muli", "Bold"],
    "Muli Light" : ["Muli", "Light"],
    "Muli Light Italic" : ["Muli", "Light Italic"],
    "Nobile" : ["Nobile", "Regular"],
    "Nobile Bold" : ["Nobile", "Bold"],
    "Nobile Bold Italic" : ["Nobile", "Bold Italic"],
    "Nobile Italic" : ["Nobile", "Italic"],
    "Noto Sans" : ["Noto Sans", "Regular"],
    "Noto Sans Bold" : ["Noto Sans", "Bold"],
    "Noto Sans Bold Italic" : ["Noto Sans", "Bold Italic"],
    "Noto Sans Italic" : ["Noto Sans", "Italic"],
    "Open Sans" : ["Open Sans", "Regular"],
    "Open Sans Bold" : ["Open Sans", "Bold"],
    "Open Sans Italic" : ["Open Sans", "Italic"],
    "Open Sans Light" : ["Open Sans", "Light"],
    "Open Sans Semibold" : ["Open Sans", "Semibold"],
    "Open Sans Condensed Light" : ["Open Sans", "Condensed Light"],
    "Oswald" : ["Oswald", "Regular"],
    "Oswald Bold" : ["Oswald", "Bold"],
    "Oswald Light" : ["Oswald", "Light"],
    "Oswald SemiBold" : ["Oswald", "SemiBold"],
    "Palanquin Dark Bold" : ["Palanquin Dark Bold", "Regular"],
    "Philosopher" : ["Philosopher", "Regular"],
    "Philosopher Bold" : ["Philosopher", "Bold"],
    "Philosopher Italic" : ["Philosopher", "Italic"],
    "Philosopher Bold Italic" : ["Philosopher", "Bold Italic"],
    "Playfair Display" : ["Playfair Display", "Regular"],
    "Playfair Display Black" : ["Playfair Display", "Black"],
    "Playfair Display Bold" : ["Playfair Display", "Bold"],
    "Playfair Display Italic" : ["Playfair Display", "Italic"],
    "Playfair Display Bold Italic" : ["Playfair Display", "Bold Italic"],
    "Poppins" : ["Poppins", "Regular"],
    "Poppins Black" : ["Poppins", "Black"],
    "Poppins Bold" : ["Poppins", "Bold"],
    "Poppins Light" : ["Poppins", "Light"],
    "Poppins SemiBold" : ["Poppins", "SemiBold"],
    "Poppins Thin" : ["Poppins", "Thin"],
    "PT Sans" : ["PT Sans", "Regular"],
    "PT Sans Narrow" : ["PT Sans", "Narrow"],
    "PT Sans Narrow Bold" : ["PT Sans", "Narrow Bold"],
    "Quattrocento Sans" : ["Quattrocento Sans", "Regular"],
    "Quattrocento Sans Bold" : ["Quattrocento Sans", "Bold"],
    "Quattrocento Sans Italic" : ["Quattrocento Sans", "Italic"],
    "Quattrocento Sans Bold Italic" : ["Quattrocento Sans", "Bold Italic"],
    "Raleway" : ["Raleway", "Regular"],
    "Raleway Black" : ["Raleway", "Black"],
    "Raleway Bold" : ["Raleway", "Bold"],
    "Raleway SemiBold" : ["Raleway", "SemiBold"],
    "Raleway Italic" : ["Raleway", "Italic"],
    "Raleway Light" : ["Raleway", "Light"],
    "Raleway Thin" : ["Raleway", "Thin"],
    "Roboto" : ["Roboto", "Regular"],
    "Roboto Black" : ["Roboto", "Black"],
    "Roboto Bold" : ["Roboto", "Bold"],
    "Roboto Thin" : ["Roboto", "Thin"],
    "Roboto Condensed" : ["Roboto Condensed", "Regular"],
    "Roboto Condensed Bold" : ["Roboto Condensed", "Bold"],
    "Roboto Condensed Light" : ["Roboto Condensed", "Light"],
    "Roboto Condensed Bold Italic" : ["Roboto Condensed", "Bold Italic"],
    "Roboto Condensed Light Italic" : ["Roboto Condensed", "Light Italic"],
    "Roboto Slab" : ["Roboto Slab", "Regular"],
    "Roboto Slab Thin" : ["Roboto Slab", "Thin"],
    "Roboto Slab Light" : ["Roboto Slab", "Light"],
    "Roboto Slab Bold" : ["Roboto Slab", "Bold"],
    "Roboto Slab Black" : ["Roboto Slab", "Black"],
    "Roboto Slab Extra Light" : ["Roboto Slab", "Extra Light"],
    "Roboto Slab Semi Bold" : ["Roboto Slab", "Semi Bold"],
    "Roboto Slab Extra Bold" : ["Roboto Slab", "Extra Bold"],
    "Roboto Slab Medium" : ["Roboto Slab", "Medium"],
    "Sansita" : ["Sansita", "Regular"],
    "Six Caps" : ["Six Caps", "Regular"],
    "Source Sans Pro" : ["Source Sans Pro", "Regular"],
    "Space Mono" : ["Space Mono", "Regular"],
    "Space Mono Bold" : ["Space Mono", "Bold"],
    "Space Mono Italic" : ["Space Mono", "Italic"],
    "Spirax" : ["Spirax", "Regular"],
    "Tahoma" : ["Tahoma", "Regular"],
    "Tahoma Bold" : ["Tahoma", "Bold"],
    "Times New Roman" : ["Times New Roman", "Regular"],
    "Times New Roman Bold" : ["Times New Roman", "Bold"],
    "Times New Roman Italic" : ["Times New Roman", "Italic"],
    "Times New Roman Bold Italic" : ["Times New Roman", "Bold Italic"],
    "Trebuchet MS" : ["Trebuchet MS", "Regular"],
    "Trebuchet MS Bold" : ["Trebuchet MS", "Bold"],
    "Trebuchet MS Italic" : ["Trebuchet MS", "Italic"],
    "Trebuchet MS Bold Italic" : ["Trebuchet MS", "Bold Italic"],
    "Verdana" : ["Verdana", "Regular"],
    "Verdana Bold" : ["Verdana", "Bold"],
    "Verdana Italic" : ["Verdana", "Italic"],
    "Verdana Bold Italic" : ["Verdana", "Bold Italic"],
    "Vollkorn" : ["Vollkorn", "Regular"],
    "Vollkorn Bold" : ["Vollkorn", "Bold"],
    "Vollkorn Italic" : ["Vollkorn", "Italic"],
    "Vollkorn Semibold" : ["Vollkorn", "Semibold"],
    "Vollkorn Bold Italic" : ["Vollkorn", "Bold Italic"],
    "Wendy One" : ["Wendy One", "Regular"],
  }
  if(fontName != null){
    return kmdsFontsStyleList[fontName]
  }
}
