<?php
//test
/*
 * @file
 * KMDS page template
*/
function media_design_system_theme($existing, $type, $theme, $path) {
  return [
    'product_list_template' => [
      'variables' => NULL,
    ],
    'product_library_template' => [
      'variables' => NULL,
    ],
    'kmds_design_tool_template' => [
      'variables' => NULL,
    ],
		'kmds_design_tool_templatex' => [
      'variables' => NULL,
    ],
		'my_kaboodles_template_test' => [
      'variables' => [
        'foo' => NULL, 
        'data' => array(), 
        'uid' => NULL,
        'archive' => NULL,
        'pager' => array(),
      ],
    ],
  ];
}