Caman.Filter.register("blackAndWhite", function(grey) {
    this.greyscale();
    this.sepia(10);
    this.exposure(10);
    this.contrast(15);
    return this.vignette("60%", 35);
});

Caman.Filter.register("bright", function(grey) {
    this.brightness(7);
    this.exposure(5);
    this.contrast(16);
    return this.vibrance(7);
});


// Generated by CoffeeScript 1.6.3
(function() {

    var text = "Uploaded file";
    var default_preset_value_new = jQuery("#mediaPreset option").filter(function() {
        return jQuery(this).text() === text;
    }).first().attr("value");

    var busy, caman, changed, filters, presetBusy, presetCaman, render, renderPreset,
        __hasProp = {}.hasOwnProperty;

    caman = null;

    presetCaman = null;

    filters = {};

    busy = false;

    changed = false;

    render = _.throttle(function() {
        jQuery('.path-tools #main-wrapper').append('<div id="overlay"><div class="km-loader"></div></div>');
        var filter, value;
        if (busy) {
            changed = true;
            return;
        } else {
            changed = false;
        }
        busy = true;
        caman.revert();
        for (filter in filters) {
            if (!__hasProp.call(filters, filter)) continue;
            value = filters[filter];
            value = parseFloat(value, 10);
            if (value === 0) {
                continue;
            }
            caman[filter](value);
        }
        return caman.render(function() {
            busy = false;
            jQuery('#overlay').remove();
            if (changed) {
                return render();
            }

        });
    }, 300);


    //click on adjust tab
    jQuery("body").on('click', '.photo-field-block #nav-adjust-tab', function(e) {
        jQuery('#myCanvas').css('display', 'block');
        jQuery('.cropit-preview').hide();
        jQuery('.image-editor-header').addClass('disabled');
        //jQuery('.FilterSetting input').trigger('change');

    });

    jQuery("#nav-adjust").on('click', '.preview-button .caman-preview', function(e) {
        var base64 = '';
        jQuery('.path-tools #main-wrapper').append('<div id="overlay"><div class="km-loader"></div></div>');
        Caman("#myCanvas", function() {
            var base64Image = this.toBase64();
            jQuery.ajax({
                url: '/bae64ToImageConversion',
                data: {
                    "mode": 'ajax',
                    "imageBase64": base64Image,
                },
                type: "POST",
                success: function(data) {
                    jQuery('.original-image').attr('data-blob', data.file_url);
                    jQuery('.original-image').attr('data-fid', data.fid);
					jQuery('.original-image').attr('data-original', 0);
                    jQuery('#nav-save-tab').trigger('click');
                    jQuery('#overlay').remove();
                    if (jQuery('#mediaPreset').val()) {
                        jQuery('#mediaPreset').trigger('change');
                    } else {
                        jQuery("select#mediaPreset option[value='" + default_preset_value_new + "']").attr('disabled', false);
                        jQuery('#mediaPreset').trigger('change');
                        jQuery("select#mediaPreset option[value='" + default_preset_value_new + "']").attr('disabled', true);
                    }

                }
            });
        });
    });

    jQuery("#nav-adjust").on('click', '.filter-wrapper.non-expert', function(e) {
        window.location.href = jQuery('.professional-role-instruction a').attr('href');
    });

    // click on save tab
    jQuery("body").on('click', '.photo-field-block #nav-save-tab', function(e) {
        jQuery('#myCanvas').css('display', 'none');
        jQuery('.cropit-preview').show();
        jQuery('.image-editor-header').removeClass('disabled');
        var can = document.getElementById("myCanvas");
        const base64Canvas = can.toDataURL("image/jpeg");
        // jQuery('.cropit-preview-image').attr('src',base64Canvas);			 
    });
    // set default value on slider dbl click
    jQuery("#Filters").on("dblclick", ".range-slider", function() {
        var default_value = jQuery(this).attr('data-default');
        jQuery(this).val(default_value);
        jQuery(this).trigger('change');
    });


    jQuery(document).ready(function() {

        var image_src = jQuery('.original-image').attr('data-blob');
        caman = Caman('#myCanvas', image_src, function() {
            this.render();
        });
        jQuery('.FilterSetting input').each(function() {
            var filter;
            filter = jQuery(this).data('filter');
            return filters[filter] = jQuery(this).val();
        });
        jQuery('#Filters').on('change', '.FilterSetting input', function() {
            var filter, value;
            filter = jQuery(this).data('filter');
            value = jQuery(this).val();
            filters[filter] = value;
            jQuery(this).find('~ .FilterValue').html(value);
            return render();
        });

    });

}).call(this);